remote_theme: pmarsceill/just-the-docs
# theme: "just-the-docs"

logo: "/assets/img/logo.png"

title: neXo knowledge base
description: The neXo products knowledge base
baseurl: "/kb" # the subpath of your site, e.g. /blog
url: "https://nexogit.github.io" # the base hostname & protocol for your site, e.g. http://example.com
